export const QUOTE_ACCOUNT=process.env.NEXT_PUBLIC_QUOTE_ACCOUNT
export const lambda = "/lambda"
export const createPolicyHolder="/policyholder/create";
export const createPolicy="/policy";
export const Url =process.env.NEXT_PUBLIC_URL
export const authUrl = "/account/authenticate";
export const products = "/products";
export const updatePolicy = "/policy/" 
export const update = "/update"
export const auxDataUrl = "/auxData/"
export const auxMin="pillarConfig/minWithdrawalAmount"
export const auxMinpolicy="pillarConfig/minPolicyAccountValue"
export const policies = "/policies"
export const discard = "/discard"
export const quotes="/quotes"
export const pandaDoc=process.env.NEXT_PUBLIC_PANDA_DOC
export const SendDoc=process.env.NEXT_PUBLIC_SEND_DOC
export const plaidURL=process.env.NEXT_PUBLIC_PLAID_URL
export const plaidcreatetoken=process.env.NEXT_PUBLIC_PLAID_CREATE_TOKEN
export const endorsements = "/endorsements"